<?php

namespace Ing200086\Envase\Tests\Unit\ValueContainer;

use Ing200086\Envase\Tests\Unit\TestCase;
use Ing200086\Envase\ValueContainer;

class ValueTestCase extends TestCase {
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_container = ValueContainer::Create();
        $this->_container->add($this->_id, $this->_entity);
    }

    protected function mock(int $id)
    {
        return strval($id);
    }
}