<?php

namespace Ing200086\Envase\Tests\Unit\Container\Generic;

use Ing200086\Envase\ValueContainer;

/**
 * Class OpenContainerTest
 *
 * @package Ing200086\Envase\Tests\Unit\Generic\Container
 *
 */
class OpenContainerTest extends TestCase {
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_container = ValueContainer::Create();
        $this->_container->add($this->_stubId, $this->_stub);
    }

    /** @test*/
    public function it_can_be_populated() {
        $this->assertTrue($this->_container->has($this->_stubId));
    }

    /** @test
     */
    public function it_can_remove_by_id() {
        $this->_container->remove($this->_stubId);

        $this->assertFalse($this->_container->has($this->_stubId));
    }
}
