<?php

namespace Ing200086\GraphCore\Tests\Unit\Container\Entity;

use Ing200086\GraphCore\Entity\EntityInterface;
use Mockery;

class TestCase extends \PHPUnit\Framework\TestCase {
    protected $_container;
    protected $_entities;
    protected $_entity;

    protected function mockEntities(int $count)
    {
        $result = [];

        for ($i = 0; $i < $count; $i++)
        {
            $result[] = $this->mockEntity(chr($i+65), $i+123);
        }

        return $result;
    }

    protected function mockEntity(string $id, int $value)
    {
        $entity = Mockery::mock(EntityInterface::class);
        $entity->shouldReceive('getId')->andReturn($id);
        $entity->shouldReceive('getValue')->andReturn($value);

        return $entity;
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Mockery::close();
    }

}