<?php

namespace Ing200086\GraphCore\Tests\Unit\Vertices;

use Mockery;
use Ing200086\GraphCore\Vertex\UnregisteredInterface;

class TestCase extends \PHPUnit\Framework\TestCase {
    protected $_container;
    protected $_vertex;
    protected $_vertices;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->_vertices = $this->mockVertexArray(10);
        $this->_vertex = $this->_vertices[0];
    }

    protected function mockVertexArray($count)
    {
        $result = [];

        for ( $i = 0; $i < $count; $i++ )
        {
            $result[] = $this->mockUnregisteredVertex($i);
        }

        return $result;
    }

    protected function mockUnregisteredVertex($id) : UnregisteredInterface
    {
        $vertex = Mockery::mock(UnregisteredInterface::class);
        $vertex->shouldReceive('getId')->andReturn(strval($id));
        $vertex->shouldReceive('getValue')->andReturn($id);

        return $vertex;
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Mockery::close();
    }
}
