<?php
namespace Ing200086\GraphCore\Tests\Unit;

use \Mockery as M;

class TestCase extends \PHPUnit\Framework\TestCase {
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        M::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
